variable "tenant" {}
variable "name" {}
variable "environment" {}
variable "vpc_id" {}
variable "cidr_block" {}
variable "subnet_ids" {}
variable "encryption" {}
variable "kms_key_id" {}
variable "efs_name" {}
variable "performance_mode" {}
variable "throughput_mode" {}
variable "provisioned_throughput_in_mibps" {}